GET http://localhost:3000/WebAPIs

###

GET  http://localhost:3000/WebAPIs

###


POST http://localhost:3000/WebAPIs

{
    "name": "'Mrs. Koffee'",
    "WebAPIsTocustomer": "Materials"


    ###
    DELETE http://localhost:3000/WebAPIs


     ###
    PATCH http://localhost:3000/WebAPIs
    Content-Type: application/json

    "name" : "Update Materials"
}